FROM python:3.10-buster

ENV PYTHONUNBUFFERED=1 \
    POETRY_VERSION=1.2.1 \
    POETRY_VIRTUALENVS_CREATE="false"

RUN pip install "poetry==$POETRY_VERSION"

WORKDIR /app

COPY pyproject.toml poetry.lock  ./
RUN poetry install --no-interaction --no-ansi --no-dev

COPY bot /app

EXPOSE 8000

CMD ["python", "main.py", "--polling"]
