FROM python:3.10-buster

ENV PYTHONUNBUFFERED=1 \
    POETRY_VERSION=1.2.1 \
    POETRY_VIRTUALENVS_CREATE="false"

RUN pip install "poetry==$POETRY_VERSION"

WORKDIR /app

COPY pyproject.toml entrypoint.sh ./
RUN poetry install --no-interaction --no-ansi --only main

COPY bot /app
COPY alembic.ini ./alembic.ini
COPY alembic ./alembic

EXPOSE 8000

RUN chmod +x entrypoint.sh

CMD ["./entrypoint.sh"]
